openapi: 3.1.0
info:
  title: Webflow Sites API
  description: Webflow Data API v2 - Sites endpoints.
  version: 2.0.0
  contact:
    name: Webflow Developer Relations
    email: developers@webflow.com
    url: https://developers.webflow.com
  termsOfService: https://webflow.com/legal/terms
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://api.webflow.com/v2
    description: Webflow API v2
security:
  - OAuth2: []
  - ApiKey: []
tags:
  - name: Site Activity
  - name: Site Administration
  - name: Sites
    description: Sites are the sites in your Webflow workspace.
  - name: Workspce Audit Logs
paths:
  /workspaces/{workspace_id}/sites:
    post:
      security:
        - OAuth2:
            - sites:write
      operationId: create-site
      summary: Webflow Create Site
      description: 'Create a site.


        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>


        Required scope | `workspace:write`

        '
      tags:
        - Sites
  /workspaces/{workspace_id_or_slug}/audit_logs:
    get:
      security:
        - OAuth2:
            - workspace_activity:read
      operationId: get-workspace-audit-logs
      summary: Webflow Get Workspace Audit Logs
      description: 'Get audit logs for a workspace.


        <Warning title="Enterprise & workspace API token only">This endpoint requires an Enterprise workspace and a workspace token with the `workspace_activity:read` scope. Create a workspace token from your workspace dashboard integrations page to use this endpoint.</Warning>


        Required scope | `workspace_activity:read`

        '
      tags:
        - Workspce Audit Logs
  /sites:
    get:
      security:
        - OAuth2:
            - sites:read
      operationId: list-sites
      summary: Webflow List Sites
      description: 'List of all sites the provided access token is able to access.


        Required scope | `sites:read`

        '
      tags:
        - Sites
  /sites/{site_id}:
    get:
      security:
        - OAuth2:
            - sites:read
      operationId: get-site
      summary: Webflow Get Site
      description: 'Get details of a site.


        Required scope | `sites:read`

        '
      tags:
        - Sites
    patch:
      security:
        - OAuth2:
            - sites:write
      operationId: update-site
      summary: Webflow Update Site
      description: 'Update a site.


        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>


        Required scope | `sites:write`

        '
      tags:
        - Sites
    delete:
      security:
        - OAuth2:
            - sites:write
      operationId: delete-site
      summary: Webflow Delete Site
      description: 'Delete a site.


        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>


        Required scope | `sites:write`

        '
      tags:
        - Sites
  /sites/{site_id}/custom_domains:
    get:
      security:
        - OAuth2:
            - sites:read
      operationId: get-custom-domains
      summary: Webflow Get Custom Domains
      description: 'Get a list of all custom domains related to site.


        Required scope | `sites:read`

        '
      tags:
        - Sites
  /sites/{site_id}/publish:
    post:
      security:
        - OAuth2:
            - sites:write
      operationId: site-publish
      summary: Webflow Publish Site
      description: 'Publishes a site to one or more more domains.


        To publish to a specific custom domain, use the domain IDs from the [Get Custom Domains](/data/reference/sites/get-custom-domain) endpoint.


        You must include at least one of the `customDomains` or `publishToWebflowSubdomain` properties in the request body.


        <Note title="Rate limit: 1 publish per minute">This endpoint has a specific rate limit of one successful publish queue per minute.</Note>


        Required scope | `sites:write`

        '
      tags:
        - Sites
  /sites/{site_id}/redirects:
    get:
      security:
        - OAuth2:
            - sites:read
      operationId: get-redirects
      summary: Webflow Get 301 redirects
      description: 'Fetch a list of all 301 redirect rules configured for a specific site.


        Use this endpoint to review, audit, or manage the redirection rules that control how traffic is rerouted on your site.


        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>


        Required scope: `sites:read`

        '
      tags:
        - Sites
    post:
      security:
        - OAuth2:
            - sites:write
      operationId: create-redirect
      summary: Webflow Create a 301 redirect
      description: 'Add a new 301 redirection rule to a site.


        This endpoint allows you to define a source path (`fromUrl`) and its corresponding destination path (`toUrl`), which will dictate how traffic is rerouted on your site. This is useful for managing site changes, restructuring URLs, or handling outdated links.


        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>


        Required scope: `sites:write`

        '
      tags:
        - Sites
  /sites/{site_id}/redirects/{redirect_id}:
    patch:
      security:
        - OAuth2:
            - sites:write
      operationId: update-redirect
      summary: Webflow Update 301 redirect
      description: 'Update a 301 redirection rule from a site.


        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>


        Required scope: `sites:write`

        '
      tags:
        - Sites
    delete:
      security:
        - OAuth2:
            - sites:write
      operationId: delete-redirects
      summary: Webflow Delete 301 redirects
      description: 'Remove a 301 redirection rule from a site.


        This is useful for cleaning up outdated or unnecessary redirects, ensuring that your site''s routing behavior remains efficient and up-to-date.


        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>


        Required scope: `sites:write`

        '
      tags:
        - Sites
  /sites/{site_id}/plan:
    get:
      security:
        - OAuth2:
            - sites:read
      operationId: get-site-plan
      summary: Webflow Get Site Plan
      description: 'Get site plan details for the specified Site.


        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>


        Required scope | `sites:read`

        '
      tags:
        - Sites
  /sites/{site_id}/robots_txt:
    get:
      security:
        - OAuth2:
            - site_config:read
      operationId: get-robots-txt
      summary: Webflow Get robots.txt
      description: 'Retrieve the robots.txt configuration for various user agents.


        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>


        Required scope: `site_config:read`

        '
      tags:
        - Sites
    put:
      security:
        - OAuth2:
            - site_config:write
      operationId: replace-robots-txt
      summary: Webflow Replace robots.txt
      description: 'Replace the `robots.txt` configuration for various user agents.


        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>


        Required scope | `site_config:write`

        '
      tags:
        - Sites
    patch:
      security:
        - OAuth2:
            - site_config:write
      operationId: update-robots-txt
      summary: Webflow Update robots.txt
      description: 'Update the `robots.txt` configuration for various user agents.


        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>


        Required scope | `site_config:write`

        '
      tags:
        - Sites
    delete:
      security:
        - OAuth2:
            - site_config:write
      operationId: delete-robots-txt
      summary: Webflow Delete robots.txt
      description: 'Remove specific rules for a user-agent in your `robots.txt` file. To delete all rules for a user-agent, provide an empty rule set. This will remove the user-agent''s entry entirely, leaving it subject to your site''s default crawling behavior.


        **Note:** Deleting a user-agent with no rules will make the user-agent''s access unrestricted unless other directives apply.


        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>


        Required scope: `site_config:write`

        '
      tags:
        - Sites
  /sites/{site_id}/well_known:
    put:
      security:
        - OAuth2:
            - site_config:write
      operationId: set-well-known
      summary: Webflow Set a well-known file
      description: "Upload a supported well-known file to a site.\n\nThe current restrictions on well-known files are as follows:\n  - Each file must be smaller than 100kb\n  - Less than 30 total files\n  - Have one of the following file extensions (or no extension): `.txt`, `.json`, `.noext`\n\n  <Note title=\".noext\">\n    `.noext` is a special file extension that removes other extensions. For example, `apple-app-site-association.noext.txt` will be uploaded as `apple-app-site-association`. Us[...]"
      tags:
        - Site Administration
        - Sites
    delete:
      security:
        - OAuth2:
            - site_config:write
      operationId: delete-well-known
      summary: Webflow Delete a well-known file
      description: 'Delete existing well-known files from a site.


        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>


        Required scope: `site_config:write`

        '
      tags:
        - Site Administration
        - Sites
  /sites/{site_id}/activity_logs:
    get:
      summary: Webflow Get Site Activity Logs
      operationId: get-site-activity-logs
      description: 'Retrieve Activity Logs for a specific Site.


        <Warning title="Enterprise Only">This endpoint requires an Enterprise workspace.</Warning>


        Required scope: `site_activity:read`

        '
      tags:
        - Site Activity
        - Sites
      security:
        - OAuth2:
            - site_activity:read
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            authorized_user:read: read details about the authorized user
            assets:read: read assets on the site
            assets:write: write assets on a site
            cms:read: read collections and items for a site
            cms:write: write to collections and items for a site
            comments:read: read comments on the site
            comments:write: write comments on the site
            custom_code:read: read custom code on the site
            custom_code:write: modify custom code on the site
            ecommerce:read: read ecommerce data
            ecommerce:write: edit ecommerce data
            forms:read: read form data
            forms:write: write form data
            pages:read: read pages on the site
            pages:write: write to pages on the site
            components:read: read component data
            components:write: write component data
            sites:read: read sites on the site
            sites:write: modify pages on the site
            users:read: read users on the site
            site_activity:read: read site activity logs
            users:write: modify users on the site
            workspace:read: read workspace resource data
            workspace:write: write workspace resource data
            site_config:read: read site configuration data
            site_config:write: write site configuration data
          authorizationUrl: https://webflow.com/oauth/authorize
          tokenUrl: https://api.webflow.com/oauth/token
    ApiKey:
      type: http
      scheme: bearer